//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Abonnement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abonnement()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int IDAbonnement { get; set; }

        [Required(ErrorMessage = "La date de début est obligatoire.")]
        [DataType(DataType.Date)]
        [Display(Name ="Date de début")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DateDebut { get; set; }

        [Required(ErrorMessage = "La date de fin est obligatoire.")]
        [DataType(DataType.Date)]
        [Display(Name = "Date de fin")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DateFin { get; set; }

        [Required(ErrorMessage = "L'heure de départ est obligatoire.")]
        [DataType(DataType.Time)]
        [Display(Name = "Heure de départ")]
        public System.TimeSpan HeureDep { get; set; }

        [Required(ErrorMessage = "L'heure d'arrivée est obligatoire.")]
        [DataType(DataType.Time)]
        [Display(Name = "Heure de départ")]
        public System.TimeSpan HeureDarr { get; set; }

        [Required(ErrorMessage ="la ville de départ est obligatoire.")]
        public int IDVilleDep { get; set; }

        [Required(ErrorMessage = "la ville d'arrivée est obligatoire.")]
        public int IDVilleDarr { get; set; }

        [Required(ErrorMessage = "Le nombre voulu est obligatoire."), Range(10,30, ErrorMessage = "Le nombre voulu minimum est 10.")]
        [Display(Name = "Nombre voulu")]
        public int NbrVoulu { get; set; }
        public Nullable<int> nbrAtteint { get; set; }
        public bool Climatisation { get; set; }
        public int IDAutocar { get; set; }
        public int IDSociete { get; set; }

        //[Required(ErrorMessage = "L'image de l'autocar est obligatoire.")]
        [Display(Name = "Image de l'autocar")]
        public string AutoImage { get; set; }
    
        public virtual Autocar Autocar { get; set; }
        public virtual Societe Societe { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual Ville Ville1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
    }
}
