//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Abonnement = new HashSet<Abonnement>();
            this.Demande = new HashSet<Demande>();
        }
    
        public int IDClient { get; set; }

        [Required(ErrorMessage ="Le nom est obligatoire.")]
        [DataType(DataType.Text)]
        [Display(Name = "nom")]
        public string Nom { get; set; }

        [Required(ErrorMessage = "Le prénom est obligatoire.")]
        [DataType(DataType.Text)]
        [Display(Name = "prénom")]
        public string prenom { get; set; }

        [Required(ErrorMessage = "L'email est obligatoire.")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Le mot de passe est obligatoire.")]
        [DataType(DataType.Password)]
        [Display(Name = "mot de passe")]

        public string MotDePasse { get; set; }

        [Required(ErrorMessage = "La vérification du mot de passe est obligatoire.")]
        [DataType(DataType.Password)]
        [Display(Name = "vérification du mot de passe")]
        [Compare("MotDePasse", ErrorMessage ="les mots de passe ne sont compatibles.")]
        public string VérifierMotDePasse { get; set; }

        [Required(ErrorMessage = "Le numéro de téléphone est obligatoire.")]
        [DataType(DataType.Text)]
        [Display(Name = "Numéro de téléphone")]
        public string Tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonnement> Abonnement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demande> Demande { get; set; }
    }
}
