//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Demande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Demande()
        {
            this.Client = new HashSet<Client>();
        }
    
        public int IDDemande { get; set; }

        [Required(ErrorMessage ="la date de debut est obligatoire.")]
        [DataType(DataType.Date)]
        [Display(Name ="Date de début")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DateDebut { get; set; }

        [Required(ErrorMessage = "la date de fin est obligatoire.")]
        [DataType(DataType.Date)]
        [Display(Name = "Date de fin")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime DateFin { get; set; }

        [Required(ErrorMessage = "la date de debut est obligatoire.")]
        [DataType(DataType.Time)]
        [Display(Name = "Heure de départ")]
        public System.TimeSpan HeureDep { get; set; }

        [Required(ErrorMessage = "la date de debut est obligatoire.")]
        [DataType(DataType.Time)]
        [Display(Name = "Heure d'arrivée")]
        public System.TimeSpan HeureDarr { get; set; }
        public int IDVilleDep { get; set; }
        public int IDVilleDarr { get; set; }
        public int IDSociete { get; set; }
    
        public virtual Societe Societe { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual Ville Ville1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Client { get; set; }
    }
}
